# **Sistemas Numéricos Computacionais.**

**Autovalores**


**prof: Sérgio Assunção Monteiro, D.Sc**

**linkedin:** https://www.linkedin.com/in/sergio-assun%C3%A7%C3%A3o-monteiro-b781897b/

**lattes:** http://lattes.cnpq.br/9489191035734025

**Exemplo 01**

In [1]:
import numpy as np
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[1 1 2 1]
 [2 9 6 9]
 [5 3 4 8]
 [5 6 9 7]]


**Exemplo 02**

In [2]:
#Criar matriz simétrica
S = P @ P.T
print(S)

[[  7  32  24  36]
 [ 32 202 133 181]
 [ 24 133 114 135]
 [ 36 181 135 191]]


**Exemplo 03**

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
A = np.array([[6,2],[2,3]])
results = la.eig(A)
print(results[0]) # Autovalores
print(results[1]) # Autovetores
autvals, autvecs = la.eig(A)
print(autvals); 
print(autvecs)

[7.+0.j 2.+0.j]
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]
[7.+0.j 2.+0.j]
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


**Exemplo 04**

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A = np.array([[2, 2, 3], 
              [1, 3, 5],
              [2, 9, 4]])
# Autovalores e Autovetores
autvals, autvecs = la.eig(A)
print(f'autvals={autvals}')
print(f'autvecs={autvecs}')

autvals=[11.07157028+0.j  1.23077943+0.j -3.30234971+0.j]
autvecs=[[ 0.36934041  0.97540635 -0.22135329]
 [ 0.52201256 -0.1758812  -0.58430159]
 [ 0.76882413 -0.13284674  0.78076525]]
